# Generated by Django 5.0.6 on 2024-06-13 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_status_delete_loanstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanapplication'),
        ),
    ]
